name: Sync
description: Sync the data from the source to the destination
permissions:
  contents: write
  issues: write
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sync
        run: python sync.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
